### ISSUE TITLE
Alias to alias is not possible

### ISSUE THREAD

**Issue by MexHigh** [scheidti/docker-mailserver-aliases#1]
You cannot set an alias to an alias. This is perfectly possible in DMS, but the addresses in  the "Redirects to" select dropdown seems to be real inbox accounts.

**Proposal:** Add a checkbox next to the "Redirects to" dropdown to include already existing aliases in it. This would make sure that the dropdown is not cluttered by default but allows the alias to alias scenario.

Thank you for this tool, I had no problems setting it up :)

**Comment by scheidti** [comment]
Hi @MexHigh,

Thank you for your feedback! I’ve added the checkbox as described in your proposal and will include these changes in release v1.1.0. If you’d like to test the changes before the release, I’ve pushed a Docker image: `chscheid/docker-mailserver-aliases:latest`, which includes the updates.

**Comment by MexHigh** [comment]
Thanks! Works like a charm.
