### ISSUE TITLE
Domain selection contains duplicates and no alias domains

### ISSUE THREAD

**Issue by MexHigh** [scheidti/docker-mailserver-aliases#2]
The domain selection in the "Create new alias selection" contains duplicates. I have multiple real inboxes on one domain. For each of this inboxes, the domain part after the @ is shown resulting in duplicates.

It should also be possible to select a domain that only has aliases (see #1). I see two possible solutions for this:
1. Add another option to the domain dropdown to let the user set the domain via an freetext input field
2. Gather all configured domains in DMS (e.g. configured for DKIM?) and add them to the dropdown

**Comment by scheidti** [comment]
I now retrieve the domain options from the real inboxes and existing aliases. This should resolve the issue without needing to load all configured domains from DMS. The duplicates should also be removed.
